# Generated by Django 4.1.5 on 2023-01-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarticle',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='articleImage/'),
        ),
    ]
